/* Auto-generated by tools/sync_symbols.py from recomp/symbols.toml.
 * Do NOT hand-edit. Progressive naming / partial-decomp address map.
 * See docs/SYMBOLS.md.
 */
#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- Function entries (24-bit PC) ---- */
#define MW_FN_I_RESET  0x0080AEu  /* confirmed emit — Emulation RESET vector ($FFFC) */
#define MW_FN_I_NMI  0x008182u  /* confirmed emit — Native NMI trampoline — PHK/PER/JML [$0000]/RTI */
#define MW_FN_I_IRQ  0x008224u  /* confirmed emit — Native IRQ vector ($FFEE) */
#define MW_FN_MwNmiBody  0x80818Au  /* confirmed — Default NMI hook target in [$0000]; healed when WRAM smash detected */
#define MW_FN_MwObjectDrawer  0x8086B6u  /* confirmed — Present-path object drawer (interp_bridge_run from host). Emits into OamStaging; H2H host captures sticky for whitelist metas. */
#define MW_FN_MwDrawObject_1P  0x808704u  /* hot — 1P drawer region — STA $86 / meta hooks at $8704/$8714/$8721 */
#define MW_FN_MwDrawObject_H2H  0x8087A0u  /* hot — H2H dual drawer (cam0 then cam1). Sites $87DE/$8802/$881F/$882F. OAM pressure often keeps 1 of N tiles — host multi-tile sticky. */
#define MW_FN_MwActiveListBuilder  0x809219u  /* guessed — Active-list / prop Y-gate / screen-X CMP cluster (~$922E..) */
#define MW_FN_MwBgDmaSetup  0x8092E4u  /* guessed — BG1/BG2 DMA size sites $92E4/$9328 (widescreen widen). Feeds StripSrc_A/B + VRAM; coldump strip.* samples post-present. */
#define MW_FN_MwStageDirtyRect  0x80943Bu  /* hot — Stage dirty-rect lo/hi builders → $1E72..$1E78 (map column dirty for $7F→VRAM) */
#define MW_FN_MwObjOnscreenTest  0x80A5ABu  /* confirmed — Object onscreen entry / BMI / CMP; objgfx caller $A5D7 */
#define MW_FN_MwBgDmaSetupAlt  0x80A838u  /* guessed — Alt DMA size sites $A838/$A87F */
#define MW_FN_MwH2hYBias  0x80B99Bu  /* hot — H2H taller OAM Y bias sites $B99B/$B9EF */
#define MW_FN_MwParticleWindow  0x80DC13u  /* hot — Particle BMI/BCS/after-STA window cluster */
#define MW_FN_MwBBoxWindow  0x82837Eu  /* hot — BBox left BCC / right BCS — cam0/cam1 pairs */
#define MW_FN_MwDistLimitSta  0x8283B2u  /* confirmed — Widen $8283AC radius STA for update/despawn callers */
#define MW_FN_MwSpawnWindow  0x82F62Au  /* hot — Spawn Y height / left STA / hi CMP cluster $F62A..$F733 */
#define MW_FN_MwH2hYBias_Bank84  0x84834Cu  /* hot — H2H taller Y bias (bank $84) */
#define MW_FN_MwObjGateHeartbeat  0x8483C6u  /* confirmed — Object gate heartbeat hook */

/* ---- Opcode hook sites (24-bit PC) ---- */
#define MW_SITE_DrawSx_1P_A  0x808704u  /* confirmed */
#define MW_SITE_DrawSx_1P_B  0x808714u  /* confirmed */
#define MW_SITE_DrawMeta_1P  0x808721u  /* confirmed */
#define MW_SITE_DrawSx_H2H_A  0x8087DEu  /* confirmed */
#define MW_SITE_DrawSx_H2H_B  0x808802u  /* confirmed */
#define MW_SITE_DrawMeta_H2H  0x80881Fu  /* confirmed */
#define MW_SITE_DrawPropReinforce  0x80882Fu  /* confirmed */
#define MW_SITE_H2hOamClear  0x809169u  /* confirmed — Staging OAM clear — cam-tag reset */
#define MW_SITE_PropListYGate_A  0x809280u  /* confirmed */
#define MW_SITE_PropListYGate_B  0x8092A0u  /* confirmed */
#define MW_SITE_DmaSizeBg1  0x8092E4u  /* confirmed — BG1 DASIZ / STA $4305 */
#define MW_SITE_DmaSizeBg2  0x809328u  /* confirmed — BG2 DASIZ / STA $4305 */
#define MW_SITE_BBoxRightAnd_A  0x8093D8u  /* confirmed — After STA $1E26 — widen WRAM */
#define MW_SITE_StageWindowLo_A  0x80943Bu  /* confirmed — Stage dirty-rect lo */
#define MW_SITE_StageWindowHi_A  0x809442u  /* confirmed — Stage dirty-rect hi */
#define MW_SITE_StageWindowLo_B  0x80944Bu  /* confirmed — Stage dirty-rect lo (pair B) */
#define MW_SITE_StageWindowHi_B  0x809452u  /* confirmed — Stage dirty-rect hi (pair B) */
#define MW_SITE_BBoxRightAnd_B  0x8094A3u  /* confirmed — After STA $1E2A — widen WRAM */
#define MW_SITE_H2hTallerStripe  0x8095A9u  /* confirmed */
#define MW_SITE_H2hDualViewHeight  0x8095AFu  /* confirmed */
#define MW_SITE_TilePatchSta7F  0x809A31u  /* confirmed — STA $7F0000,X door/platform tile patches into shared $7F map (BG1 brown source for present rebuild) */
#define MW_SITE_TileHelper_C  0x809A3Eu  /* confirmed */
#define MW_SITE_TileHelper_A  0x809A61u  /* confirmed */
#define MW_SITE_TileHelper_B  0x809A83u  /* confirmed */
#define MW_SITE_BBoxPaddedLeftBcc  0x809B43u  /* confirmed */
#define MW_SITE_ObjOnscreenEntry  0x80A5ABu  /* confirmed */
#define MW_SITE_ObjOnscreenBmi  0x80A5B6u  /* confirmed */
#define MW_SITE_ObjOnscreenCmp  0x80A5BAu  /* confirmed */
#define MW_SITE_ObjGfxCaller  0x80A5D7u  /* confirmed */
#define MW_SITE_DmaSizeAlt1  0x80A838u  /* confirmed — Alt DMA size site */
#define MW_SITE_DmaSizeAlt2  0x80A87Fu  /* confirmed — Alt DMA size site */
#define MW_SITE_H2hYBias_A  0x80B99Bu  /* confirmed */
#define MW_SITE_H2hYBias_B  0x80B9EFu  /* confirmed */
#define MW_SITE_BBoxLeftBcc_Cam0  0x82837Eu  /* confirmed */
#define MW_SITE_BBoxRightBcs_Cam0  0x828383u  /* confirmed */
#define MW_SITE_BBoxLeftBcc_Cam1  0x828397u  /* confirmed */
#define MW_SITE_BBoxRightBcs_Cam1  0x82839Cu  /* confirmed */
#define MW_SITE_DistLimitSta  0x8283B2u  /* confirmed */
#define MW_SITE_SpawnYHeight  0x82F62Au  /* confirmed */
#define MW_SITE_H2hTallerSpawnY_A  0x82F709u  /* confirmed */
#define MW_SITE_H2hTallerSpawnY_B  0x82F721u  /* confirmed */
#define MW_SITE_H2hTallerSpawnY_C  0x82F733u  /* confirmed */
#define MW_SITE_H2hYBias_C  0x84834Cu  /* confirmed */
#define MW_SITE_ObjGateHeartbeat  0x8483C6u  /* confirmed */

/* ---- Site groups (comma-separated 24-bit PCs) ---- */
/* confirmed — Meta-sprite OAM X window widen */
#define MW_SITE_LIST_SpriteWinCmp  0x808BD5u, 0x808C85u, 0x808CCEu, 0x808D2Eu, 0x808DEEu, 0x808E3Eu, 0x808E9Eu, 0x808F5Eu, 0x808FAEu, 0x809015u, 0x8090DCu, 0x809133u
#define MW_SITE_LIST_SpriteWinCmp_COUNT  12u

/* confirmed */
#define MW_SITE_LIST_ParticleBmi  0x80DC13u, 0x80DC97u, 0x80DCCFu
#define MW_SITE_LIST_ParticleBmi_COUNT  3u

/* confirmed */
#define MW_SITE_LIST_ParticleBcs  0x80DC18u, 0x80DC9Cu, 0x80DCD4u
#define MW_SITE_LIST_ParticleBcs_COUNT  3u

/* confirmed */
#define MW_SITE_LIST_ParticleAfterSta  0x80DC1Du, 0x80DCA1u, 0x80DCD9u
#define MW_SITE_LIST_ParticleAfterSta_COUNT  3u

/* confirmed — CMP #$FFC0 after screen-X SBC */
#define MW_SITE_LIST_ActiveLoCmp  0x80922Eu, 0x80926Bu, 0x80928Bu
#define MW_SITE_LIST_ActiveLoCmp_COUNT  3u

/* confirmed — CMP #$0140 after screen-X lo */
#define MW_SITE_LIST_ActiveHiCmp  0x809233u, 0x809270u, 0x809290u
#define MW_SITE_LIST_ActiveHiCmp_COUNT  3u

/* confirmed */
#define MW_SITE_LIST_SpawnLeftSta  0x82F703u, 0x82F71Bu, 0x82F72Du
#define MW_SITE_LIST_SpawnLeftSta_COUNT  3u

/* confirmed */
#define MW_SITE_LIST_SpawnHiCmp  0x82F66Au, 0x82F67Bu
#define MW_SITE_LIST_SpawnHiCmp_COUNT  2u

/* confirmed */
#define MW_SITE_LIST_SpawnLeftBmi  0x82F668u, 0x82F679u
#define MW_SITE_LIST_SpawnLeftBmi_COUNT  2u

/* ---- WRAM / objects ---- */
#define MW_WRAM_NmiHookPtr  0x0000u  /* u8[3]; confirmed — 24-bit NMI body pointer; normally $80:818A */
#define MW_WRAM_Bg1MapPitch  0x00B6u  /* u16; confirmed — BG1 $7F row pitch in bytes; host falls back to $0290 if <32. Used by snap/present/coldump strip. */
#define MW_WRAM_OamStaging  0x14C4u  /* u8[512]; confirmed — OAM staging buffer (low table) */
#define MW_WRAM_OamStagingHi  0x16C4u  /* u8[32]; confirmed — High OAM bits; clear path walks $14C4 → $16C4 */
#define MW_WRAM_ObjectPoolBase  0x1934u  /* MwObject; confirmed — Common object pool base; stride 0x1C through ~$2000. Pool slots recycle — coldump o= is not a stable identity; bind by meta+world, not address. */
#define MW_WRAM_ObjectListHead  0x1E14u  /* u16; confirmed — Live object list head → linked MwObject records. Coldump near[] walks this list. */
#define MW_WRAM_Cam0_X  0x1E16u  /* u16; confirmed — Camera 0 world X (NMI latch / present local for slot 0) */
#define MW_WRAM_Cam0_Y  0x1E18u  /* u16; confirmed */
#define MW_WRAM_Cam1_X  0x1E1Au  /* u16; confirmed — Camera 1 world X (H2H dual; present local for slot 1) */
#define MW_WRAM_Cam1_Y  0x1E1Cu  /* u16; confirmed */
#define MW_WRAM_ScrollH0_P1  0x1E2Eu  /* u16; confirmed — WRAM BG1 H scroll sample for P1 path (NMI). Full-frame present uses applied pscroll, not raw fine alone. */
#define MW_WRAM_ScrollH0_P2  0x1E32u  /* u16; confirmed — NOT P2 world camera X — coldump d1h vs loc was always huge. Use Cam1_X / BG1 snap cam for P2 world. */
#define MW_WRAM_StripSrc_A  0x1E36u  /* u16; confirmed — BG1 strip source pointer ($7F base for DMA/present). Dual may stomp; per-cam snap fills voids. */
#define MW_WRAM_StripSrc_B  0x1E38u  /* u16; confirmed — BG2 strip source pointer */
#define MW_WRAM_ScrollH1_P1  0x1E42u  /* u16; confirmed — WRAM BG2 H scroll (P1 path) */
#define MW_WRAM_ScrollH1_P2  0x1E46u  /* u16; confirmed — WRAM BG2 H scroll (P2 path) */
#define MW_WRAM_ScrollV0_P1  0x1E5Eu  /* u16; confirmed — WRAM BG1 V scroll (P1 path) */
#define MW_WRAM_ScrollV1_P1  0x1E60u  /* u16; confirmed — WRAM BG2 V scroll (P1 path) */
#define MW_WRAM_ScrollV0_P2  0x1E62u  /* u16; confirmed — WRAM BG1 V scroll (P2 path) */
#define MW_WRAM_ScrollV1_P2  0x1E64u  /* u16; confirmed — WRAM BG2 V scroll (P2 path) */
#define MW_WRAM_DualViewportFlag  0x1EB2u  /* u16; confirmed — Nonzero ⇒ H2H dual viewport active (MwIsDualViewport) */

/* ---- Struct layouts (host-side documentation typedefs) ---- */
/* Heuristic object record — see docs/H2H_STAGE_PROPS.md §1 */
typedef struct __attribute__((packed)) {
  uint16_t flags;  /* +$00 — bit15 = active */
  uint16_t world_x;  /* +$02 */
  uint16_t world_y;  /* +$04 */
  uint16_t dual_tag;  /* +$06 — hi = viewport owner; lo = instance id (not home) */
  uint16_t meta_lo;  /* +$08 — sprite/meta id. See meta catalog above. Whitelist movers: $C382/$C39E/$C6A4/$C400/$C5F2/$C3EC/$C3C4. $D5B8=BG2 elev. $E442/$E30E=mech. Coldump m= is decimal. */
  uint16_t meta_hi;  /* +$0A — bank/class: $00B1 movers+items; $00AD dual mechs (body/sub). Coldump near[].cls uses bank + whitelist + dual_tag hi. */
  uint16_t c;  /* +$0C */
  uint16_t e;  /* +$0E — state / anim-ish */
  uint16_t w10;  /* +$10 */
  uint16_t w12;  /* +$12 */
  uint16_t next;  /* +$14 — next list link; remaining bytes to 0x1C are undocumented */
  uint8_t _pad_tail[6];
} MwSym_MwObject;
#ifdef __cplusplus
static_assert(sizeof(MwSym_MwObject) == 0x1C, "MwSym_MwObject size");
#else
_Static_assert(sizeof(MwSym_MwObject) == 0x1C, "MwSym_MwObject size");
#endif

#ifdef __cplusplus
}
#endif
